import { Request, Response, NextFunction } from 'express';
import { Client, Connection } from '@temporalio/client';
import { v4 as uuidv4 } from 'uuid';
import { 
  CreateCampaignRequest,
  CreateCampaignResponse,
  ApproveCampaignRequest,
  ApiError,
  CampaignStatus,
  ApprovalStatus,
  SocialPlatform,
  Approval
} from '../../types';
import { campaignWorkflow } from '../../workflows/campaign.workflow';
import config from '../../config';
import logger from '../../utils/logger';
import { mockDatabase } from '../../workflows/activities';

interface AuthRequest extends Request {
  user?: any;
}

// Temporal client instance
let temporalClient: Client;

const getTemporalClient = async (): Promise<Client> => {
  if (!temporalClient) {
    const connection = await Connection.connect({
      address: config.temporal.address,
    });
    temporalClient = new Client({
      connection,
      namespace: config.temporal.namespace,
    });
  }
  return temporalClient;
};

// Create a new campaign
export const createCampaign = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { title, description, platforms } = req.body as CreateCampaignRequest;
    const userId = req.user.id;

    // Validate platforms
    const validPlatforms = Object.values(SocialPlatform);
    const invalidPlatforms = platforms.filter(p => !validPlatforms.includes(p));
    if (invalidPlatforms.length > 0) {
      throw new ApiError(400, `Invalid platforms: ${invalidPlatforms.join(', ')}`);
    }

    // Generate campaign ID
    const campaignId = uuidv4();

    // Start Temporal workflow
    const client = await getTemporalClient();
    const handle = await client.workflow.start(campaignWorkflow, {
      taskQueue: 'social-campaign-queue',
      workflowId: `campaign-${campaignId}`,
      args: [{
        campaignId,
        userId,
        title,
        description,
        platforms,
      }],
    });

    logger.info('Campaign workflow started', { campaignId, workflowId: handle.workflowId });

    // Return initial response (workflow will handle the rest)
    const response: CreateCampaignResponse = {
      campaign: {
        id: campaignId,
        userId,
        title,
        description,
        status: CampaignStatus.DRAFT,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      posts: [], // Posts will be generated by the workflow
    };

    res.status(201).json({
      success: true,
      data: response,
      workflowId: handle.workflowId,
    });
  } catch (error) {
    next(error);
  }
};

// Get campaign details
export const getCampaign = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    // In production, this would query the database
    // For now, check mock database
    const campaign = mockDatabase.campaigns.get(id);
    if (!campaign || campaign.userId !== userId) {
      throw new ApiError(404, 'Campaign not found');
    }

    // Get associated posts
    const posts = Array.from(mockDatabase.posts.values()).filter(
      post => post.campaignId === id
    );

    res.json({
      success: true,
      data: {
        campaign,
        posts,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Get all campaigns for a user
export const getCampaigns = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const userId = req.user.id;
    const { status, limit = 10, offset = 0 } = req.query;

    // In production, this would query the database with pagination
    let campaigns = Array.from(mockDatabase.campaigns.values()).filter(
      campaign => campaign.userId === userId
    );

    // Filter by status if provided
    if (status) {
      campaigns = campaigns.filter(campaign => campaign.status === status);
    }

    // Apply pagination
    const total = campaigns.length;
    campaigns = campaigns.slice(Number(offset), Number(offset) + Number(limit));

    res.json({
      success: true,
      data: {
        campaigns,
        pagination: {
          total,
          limit: Number(limit),
          offset: Number(offset),
        },
      },
    });
  } catch (error) {
    next(error);
  }
};

// Approve or reject a campaign
export const approveCampaign = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const { approved, comments } = req.body as ApproveCampaignRequest;
    const userId = req.user.id;

    // Verify campaign exists and belongs to user
    const campaign = mockDatabase.campaigns.get(id);
    if (!campaign || campaign.userId !== userId) {
      throw new ApiError(404, 'Campaign not found');
    }

    // Check if campaign is in pending approval status
    if (campaign.status !== CampaignStatus.PENDING_APPROVAL) {
      throw new ApiError(400, 'Campaign is not pending approval');
    }

    // Create approval record
    const approval: Approval = {
      id: uuidv4(),
      campaignId: id,
      userId,
      status: approved ? ApprovalStatus.APPROVED : ApprovalStatus.REJECTED,
      comments,
      approvedAt: approved ? new Date() : undefined,
      rejectedAt: !approved ? new Date() : undefined,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    mockDatabase.approvals.set(approval.id, approval);

    // Update campaign status
    campaign.status = approved ? CampaignStatus.APPROVED : CampaignStatus.FAILED;
    campaign.updatedAt = new Date();

    logger.info('Campaign approval processed', { 
      campaignId: id, 
      approved, 
      status: campaign.status 
    });

    res.json({
      success: true,
      data: {
        approval,
        campaign,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Get campaign metrics
export const getCampaignMetrics = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    // Verify campaign exists and belongs to user
    const campaign = mockDatabase.campaigns.get(id);
    if (!campaign || campaign.userId !== userId) {
      throw new ApiError(404, 'Campaign not found');
    }

    // Get posts for the campaign
    const posts = Array.from(mockDatabase.posts.values()).filter(
      post => post.campaignId === id
    );

    // Get metrics for each post
    const postMetrics = posts.map(post => {
      const metrics = Array.from(mockDatabase.metrics.values()).filter(
        metric => metric.postId === post.id
      );
      
      // Get latest metrics for each post
      const latestMetrics = metrics.sort((a, b) => 
        b.fetchedAt.getTime() - a.fetchedAt.getTime()
      )[0];

      return {
        post,
        metrics: latestMetrics || null,
      };
    });

    // Calculate aggregate metrics
    const aggregateMetrics = postMetrics.reduce(
      (acc, { metrics }) => {
        if (metrics) {
          acc.totalLikes += metrics.likes;
          acc.totalComments += metrics.comments;
          acc.totalShares += metrics.shares;
          acc.totalImpressions += metrics.impressions;
          acc.totalClicks += metrics.clicks;
          acc.totalReach += metrics.reach;
        }
        return acc;
      },
      {
        totalLikes: 0,
        totalComments: 0,
        totalShares: 0,
        totalImpressions: 0,
        totalClicks: 0,
        totalReach: 0,
      }
    );

    res.json({
      success: true,
      data: {
        campaign,
        posts: postMetrics,
        aggregateMetrics,
      },
    });
  } catch (error) {
    next(error);
  }
};

// Delete a campaign
export const deleteCampaign = async (
  req: AuthRequest,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    const { id } = req.params;
    const userId = req.user.id;

    // Verify campaign exists and belongs to user
    const campaign = mockDatabase.campaigns.get(id);
    if (!campaign || campaign.userId !== userId) {
      throw new ApiError(404, 'Campaign not found');
    }

    // Check if campaign can be deleted (not published)
    if (campaign.status === CampaignStatus.PUBLISHED) {
      throw new ApiError(400, 'Cannot delete published campaigns');
    }

    // Delete campaign and related data
    mockDatabase.campaigns.delete(id);
    
    // Delete associated posts
    Array.from(mockDatabase.posts.entries()).forEach(([postId, post]) => {
      if (post.campaignId === id) {
        mockDatabase.posts.delete(postId);
      }
    });

    // Delete associated approvals
    Array.from(mockDatabase.approvals.entries()).forEach(([approvalId, approval]) => {
      if (approval.campaignId === id) {
        mockDatabase.approvals.delete(approvalId);
      }
    });

    logger.info('Campaign deleted', { campaignId: id });

    res.json({
      success: true,
      message: 'Campaign deleted successfully',
    });
  } catch (error) {
    next(error);
  }
};
